### ISSUE TITLE
[ckan-protocol] Use CKAN data in "hadoop jar" command by downloading it to HDFS

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-connectors#267]
The simplest way to use CKAN data in a Hadoop deployment is by downloading such data into HDFS. 

It is simple because it is not necessary to make a hard modification in the Hadoop sources, it is enough by modifying the `hadoop` script with sentences invoking the CKAN API (or another script or application) in order to donwload the data to a temporal HDFS file.

This is not the real goal of the `ckan-protocol` connector, which is to make such a hard modification in order to read the data "block by block". But could help in designing the connection with CKAN and analyzing which methods from the API to use.

**Comment by frbattid** [comment]
Closed since a specific repo has been created for this (https://github.com/telefonicaid/fiware-tidoop/issues/1) and other issues related to Hadoop extensions (Tidoop).

**Comment by mootazmansouri** [comment]
hi

**Comment by mootazmansouri** [comment]
hi ,i was wondering how is it possible to download ckan content in hdfs 
i know you just mentionned tht it's simple , but i'm new to hadoop and java programming , plus the ckan4j 
is not very well documented.
