### ISSUE TITLE
Packaging bug

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-connectors#313]
With the changes in the issue [#299](https://github.com/telefonicaid/fiware-connectors/issues/299) a bug was introduced in the package: templates for the config files wasn't packaged in the RPM.

Moreover three issues more will be fixed:
- in init.d script, in start option, check if no instances are configured and in this case show a error message indicating to the user to read README.md file to configure at least one instance
- in file `fiware-connectors/flume/conf/agent.conf.template` there are a line referencing `cygnus.conf` and it should be `agent.conf`
- a typo in `fiware-connectors/flume/conf/cygnus_instance.conf.template` file is detected and replaced: cugnus by cygnus

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-connectors/pull/314
