### ISSUE TITLE
Model entities parsing

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-connectors#317]
There are some special entities managed by Orion Context Broker, called <i>model entities</i>, that Cygnus must parse in order to implement other issues (https://github.com/telefonicaid/fiware-connectors/issues/315).

For instance:

```
"id": "netrisModel",
"isPattern": "false",
"type": "model",
"attributes": [
{
"name": "TimeInstant",
"type": "ISO8601",
"value": "2014-03-20T14:21:14Z"
},
{
"name": "ModelProp1",
"type": "String",
"value": “abc”
},
{
"name": "ModelProp2",
"type": "String",
"value": “def”
},
{
"name": "te",
"type": "compound",
"value":
{
"name": "Temperatura Exterior",
"phenomenon": "temperature",
      	"type": "Quantity",
"uom": "Cel",
“persistence”: “sth,ckan”
}
},
{
"name": "ti",
"type": "compound",
"value": [
{
"name": "Temperatura Interior",
"phenomenon": "temperature",
      	"type": "Quantity",
"uom": "Cel"
}
]
},
{
"name": "h",
"type": "compound",
"value": [
{
"name": "Humedad casa",
"phenomenon": "humidity",
      	"type": "Quantity",
"uom": "%"
}
]
},
{
"name": "reset",
"type": "compound",
"value": [
{
"type": "action",
"input_params": "reqTimeInstant,correlatorID,param_a,param_b",
"output_params": "result,resTimeIntant,param_c,param_d",
}
]
},
{
"name": "color",
"type": "compound",
"value": [
{
"type": "action",
"input_params": "reqTimeInstant,correlatorID",
"output_params": "result,resTimeInstant",
}
]
}

]
```

@fgalan : is there a counterpart for these entities in XML format? Or is it exclusive to Json?

**Comment by fgalan** [comment]
From a CB point of view, every entity has always the two renders: XML and JSON. However, by the case of use we are considering for these model entities, I think that JSON is enough. I mean, if Cygnus queries (using queryContext) or subscribe (using subscribeContext) to this entities in JSON, the information will be sent to Cygnus always in JSON, so you can forget about XML is you want.

**Comment by frbattid** [comment]
Having a look to the code, it seems it is already prepared to parse such a model entity notification, what is great! :) I simply forget complex attributes parsing was already implemented.

I think this issue becomes a validation check. As much, specific unit test may be added to `NotifyContextRequestTest.java`.

**Comment by frbattid** [comment]
Implemented in PR https://github.com/telefonicaid/fiware-connectors/pull/318

Really, nothing has been implemented regarding the model estities parsing since this was something already implemented. What has been done was to implement a testing purpose sink, OrionTestSink in charge of printing (logging) the content of a parsed notification; if this printing is possible, that means the notification was properly parsed.

In addition, a OrionTestSink.md document has been created (in the future, all the sinks must have an associated document as this one).
