### ISSUE TITLE
Service script (/etc/init.d/cygnus) improvement

### ISSUE THREAD

**Issue by vgarciag** [telefonicaid/fiware-connectors#332]
At this moment init script for Cygnus can start/stop/status all instances configured in Cygnus but can't start/stop/status only one instance of all the configured. 

This useful improvement, already implemented in deployment stage, should be implemented in Cygnus SW.

Then, if we have 2 instances of cygnus configured as `test1` and `test2` in `/usr/cynus/conf` for example:

`sudo service cygnus start` -> this command will start both instances if they were stopped

`sudo service cygnus start test2` -> this command  will start only `test2` instance if it was stopped

**Effort: 1 man day**

**Comment by fgalan** [comment]
This issue should have one of the follosing main labels: "backlog", "bug" or "techdebt".

In the case of the techdebt, it should have one of the following in addtion: "nicetovhave", "should", "must".

In the case of techdebt, an effort stimation should be included in the issue body (needed for the tech debt metric measure).

**Comment by fgalan** [comment]
Use integers for effort (rounding up, i.e. 2 in this case). Using 1/2 in that place cause the measuring script going crazy :)

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-connectors/pull/333
