### ISSUE TITLE
Subscription example within the README is wrong

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-connectors#346]
Currently it is (only relevant part):

```
<entityIdList>
    <entityId type="Room" isPattern="false">
      <id>Room1</id>
    </entityId>
<entityIdList>
```
It must be:

```
<entityIdList>
    <entityId type="Room" isPattern="false">
      <id>Room1</id>
    </entityId>
</entityIdList>
```

**Comment by kzangeli** [comment]
Hard to see the difference ... [ The slash is missing in the end-tag of entityIdList ] :-)

**Comment by frbattid** [comment]
@kzangeli : really hard to see it... the bug has been there for a year or more! :)

Fixed in PR https://github.com/telefonicaid/fiware-connectors/pull/350
