### ISSUE TITLE
In rpm installation, includes flume-conf.properties.template file in /us/cygnus/conf/

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/fiware-connectors#348]
The `flume-conf.properties.template` file should not be in /usr/cygnus/conf because it is a template from apache flume and not of the cygnus application.

Also, in README.md in conf folder, append `flume-env.sh.template` in: 
```
1- Unique files for all instances

For them is necessary rename (or better copy) it without .template extension. These files are: 
log4j.properties.template, krb5.conf.template and matching_table.conf.template, flume-env.sh.template
```

**Comment by vgarciag** [comment]
If this file is unnecessary it would better remove it from Git in order to not to confuse the user.

**Comment by frbattid** [comment]
Fixed in PR https://github.com/telefonicaid/fiware-connectors/pull/352
